// <auto-generated />
namespace Covid.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Covid01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Covid01));
        
        string IMigrationMetadata.Id
        {
            get { return "202110051245457_Covid01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
